<?php
 
require_once '/home/cordoval/sites-2/FormModelProjectBundle/vendor/bundles/Cordova/Bundle/FormModelBundle/Calculator/Example.php';
 
/**
 * Test class for Example.
 * Generated by PHPUnit on 2011-07-27 at 12:59:50.
 */
class ExampleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Example
     */
    protected $object;
 
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Example;
    }
 
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
 
    /**
     * @test
     * @todo ImplementshouldApplyPenaltyWhenMissingPapers().
     */
    public function shouldApplyPenaltyWhenMissingPapers()
    {
        // Remove the following lines when you implement this spec.

    }
 
    /**
     * @test
     * @todo ImplementshouldApplyPenaltyWhenDamageIsPresent().
     */
    public function shouldApplyPenaltyWhenDamageIsPresent()
    {
        // Remove the following lines when you implement this spec.
        
    }
}
?>